import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='fr'>
      <body className={inter.className}>
        <main className='m-20'>
          <ul>
            <li>
              <Link href='/'>Home</Link>
            </li>
            <li>
              <Link href='/cv'>CV</Link>
            </li>
            <li>
              <a
                target='_blank'
                href='https://www.youtube.com/@developpeurreactnord729'
              >
                YouTube
              </a>
            </li>
            <li>
              <a
                target='_blank'
                href='https://www.linkedin.com/in/gabrielbrun/'
              >
                Linkedin
              </a>
            </li>
            <li>
              <a target='_blank' href='https://github.com/lydstyl'>
                Github
              </a>
            </li>
          </ul>
          <div className='mt-20'>{children}</div>
        </main>
      </body>
    </html>
  )
}
